### ISSUE TITLE
Requests dependency missing

### ISSUE THREAD

**Issue by karlism** [corpusops/bitwardentools#10]
Hello,

After installing `bitwardentools` module on freshly installed RHEL 8 VM with Python 3.9, following error appears during `bitwardentools` python module import:
```
$ python3
Python 3.9.2 (default, May 20 2021, 01:29:22) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1.0.1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitwardentools import Client;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/bitwardentools/__init__.py", line 1, in <module>
    from bitwardentools.client import *  # noqa
  File "/usr/local/lib/python3.9/site-packages/bitwardentools/client.py", line 22, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>> 
```
Installation of `py39-requests` RPM package resolves this issue, so I guess that `requests` module is missing in `bitwardentools` dependencies.

**Comment by kiorky** [comment]
1.0.55 will ensure it.
