### ISSUE TITLE
raising keyerror on 'kdfIterations'

### ISSUE THREAD

**Issue by InterStella0** [corpusops/bitwardentools#15]
Issue when login in with the client.
## Code 
```python
self.bitwarden_client = client = Client(
   server="https://vault.bitwarden.com", 
   email=self.BITWARDEN_EMAIL, 
   password=self.BITWARDEN_PASSWORD
)
```
## Error
```python
←[31mERROR←[0m:    
Traceback (most recent call last):
  File "c:\users\sarah\pycharmprojects\stella_manager\venv\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "c:\users\sarah\pycharmprojects\stella_manager\venv\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "c:\users\sarah\pycharmprojects\stella_manager\venv\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\sarah\PycharmProjects\stella_manager\.\main.py", line 10, in starter
    await api.startup()
  File "C:\Users\sarah\PycharmProjects\stella_manager\.\core\models.py", line 41, in startup
    await asyncio.to_thread(self.startup_sync)
  File "C:\Users\sarah\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\sarah\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\sarah\PycharmProjects\stella_manager\.\core\models.py", line 30, in startup_sync
    self.bitwarden_client = client = Client(
  File "c:\users\sarah\pycharmprojects\stella_manager\venv\lib\site-packages\bitwardentools\client.py", line 719, in __init__
    self.login()
  File "c:\users\sarah\pycharmprojects\stella_manager\venv\lib\site-packages\bitwardentools\client.py", line 798, in login
    iterations = jdata["KdfIterations"]
KeyError: 'KdfIterations'
```
After investigating, the dictionary in jdata outputs the following
```python
{'kdf': 0, 'kdfIterations': 5000}
```
So it seems like they changed the key capitalization.

**Comment by kiorky** [comment]
released 1.0.52
