### ISSUE TITLE
Argon2id algorithm support?

### ISSUE THREAD

**Issue by Garulf** [corpusops/bitwardentools#26]
When attempting to login to a vaultwarden instance using argon2id the program crashes with a invalid username or password.

![image](https://github.com/corpusops/bitwardentools/assets/535299/a4c6cf78-4e10-48bc-9049-b589d3d698d7)

```
from bitwardentools import Client


client = Client(SERVER, EMAIL, PASSWORD)


client.sync()
```

```
Traceback (most recent call last):
  File "E:\Users\Garulf\Projects\Garulf\bitwarden-flow\src\plugin.py", line 11, in <module>
    client = Client(SERVER, EMAIL, PASSWORD)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\Garulf\Projects\Garulf\bitwarden-flow\.venv\Lib\site-packages\bitwardentools\client.py", line 728, in __init__
    self.login()
  File "E:\Users\Garulf\Projects\Garulf\bitwarden-flow\.venv\Lib\site-packages\bitwardentools\client.py", line 829, in login
    raise exc
bitwardentools.client.LoginError: Failed login for *****@****.com ()
```

This is the text response from the server:
```
{"ErrorModel":{"Message":"Username or password is incorrect. Try again","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Username or password is incorrect. Try again","Object":"error","ValidationErrors":{"":["Username or password is incorrect. Try again"]},"error":"","error_description":""}
```

**Comment by kiorky** [comment]
fixed in latest release.

**Comment by kiorky** [comment]
bitwardentools dev is halted.
