### ISSUE TITLE
Missing dependency - ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by commonism** [corpusops/bitwardentools#27]
When after installing bitwardentools in an empty 3.12 venv
```
>>> import bitwardentools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/demo/lib/python3.12/site-packages/bitwardentools/__init__.py", line 1, in <module>
    from bitwardentools.client import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/demo/lib/python3.12/site-packages/bitwardentools/client.py", line 24, in <module>
    from packaging import version as _version
ModuleNotFoundError: No module named 'packaging'
```

installing packaging from pip helped.

**Comment by kiorky** [comment]
fixed in latest release.
